# Test program for the SE-One cartridge

This is a small MSX-DOS utility for using the SE-One cartrigde.

Usage: seone <command>

The given command should be without the "AT+" prefix, which is generated by the program itself.
